# Generated by Django 3.1.3 on 2021-06-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Becomepartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('residential_address', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=70)),
                ('become_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='become_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferallPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(max_length=25)),
                ('service', models.CharField(max_length=35)),
                ('perform_name', models.CharField(max_length=45)),
                ('dateofperformance', models.DateField()),
                ('refarall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.becomepartner')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('state', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('profile_type', models.CharField(default='', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('action', models.CharField(default='Active', max_length=200)),
                ('current_users_count', models.PositiveIntegerField(default=0)),
                ('download_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.becomepartner')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('counting', models.PositiveIntegerField(default=0)),
                ('last_downloaded_on', models.CharField(default='', max_length=200)),
                ('download_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.becomepartner')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=35)),
                ('volume', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('commision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.becomepartner')),
            ],
        ),
        migrations.CreateModel(
            name='ApproveRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=35)),
                ('volume', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('approverate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.becomepartner')),
            ],
        ),
    ]
