# Generated by Django 3.1.3 on 2021-06-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomepartner',
            name='is_partner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='becomepartner',
            name='password',
            field=models.CharField(blank=True, default='admin', max_length=8, null=True),
        ),
    ]
