# Generated by Django 3.2 on 2021-07-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20210625_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomepartner',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
