# Generated by Django 3.1.3 on 2021-06-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilesIOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('country', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('profile_type', models.CharField(default='', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles_ios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfilesAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('country', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('profile_type', models.CharField(default='', max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles_android', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('password', models.CharField(default='', max_length=300)),
                ('phone_no', models.CharField(default='', max_length=200, unique=True)),
                ('designation', models.CharField(default='', max_length=200)),
                ('function_names', models.CharField(default='', max_length=2000)),
                ('permission_types', models.CharField(default='', max_length=200)),
                ('password_revovery_key', models.CharField(default='', max_length=200)),
                ('action', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BecomeMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(default='')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address3', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('zipcode', models.IntegerField(default='')),
                ('pancard', models.CharField(blank=True, max_length=10, null=True)),
                ('aadharcard', models.IntegerField(default='')),
                ('photo', models.FileField(blank=True, null=True, upload_to='become_member/')),
                ('action', models.BooleanField(blank=True, default=False, null=True)),
                ('become_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='become_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Become_member',
            },
        ),
    ]
