# Generated by Django 3.1.3 on 2021-06-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomemember',
            name='password',
            field=models.CharField(blank=True, default='admin', max_length=8, null=True),
        ),
    ]
