# Generated by Django 3.1.3 on 2021-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210618_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomemember',
            name='is_member',
            field=models.BooleanField(default='True'),
        ),
    ]
