from .viewsets import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('CountryCode', CountryCodeViewset)
router.register('managenewsmedia', ManageNewsMediaViewset)
router.register('manageseocontent', ManageSEOContentViewset)
router.register('postvacancies', PostVacanciesViewset)
router.register('resumereceipt', ResumeReceiptViewset)
router.register('publishblogs', PublishBlogsViewset)
router.register('approvecomments', ApproveCommentsViewset)
router.register('partners', PartnersViewset)
router.register('testimonials', TestimonialsViewset)
router.register('mobileappandroid', MobileAppAndroidViewset)
router.register('mobileappios', MobileAppIOSViewset)
router.register('totaldownloadsandroid', TotalDownloadsAndroidViewset)
router.register('totaldownloadsios', TotalDownloadsIOSViewset)
router.register('singledownloadandroid', SingleDownloadAndroidViewset)
router.register('singledownloadios', SingleDownloadIOSViewset)
router.register('onlineusersandroid', OnlineUsersAndroidViewset)
router.register('onlineusersios', OnlineUsersIOSViewset)
router.register('backup', BackupViewset)
router.register('synchronisation', SynchronisationViewset)
router.register('restore', RestoreViewset)
router.register('feedback', FeedbackViewset)
router.register('reviews', ReviewsViewset)
router.register('managesubscription', ManageSubscriptionViewset)
router.register('subscribers', SubscribersViewset)
router.register('support', SupportViewset)

router.register('commission', CommissionViewset)
router.register('approverate', ApproveRateViewset)
router.register('refferalpartner', ReferallPartnerViewset)
router.register('partnerpayout', PartnerPayoutStructureViewset)
router.register('transactionhistory', TransactionHistoryViewset)
router.register('referandearn', ReferAndEarnViewset)
router.register('phoneconversation', PhoneConversationViewset)
router.register('chatbot', ChatBotViewset)
router.register('ticket', TicketViewset)
router.register('mail',MailViewset)
router.register('discount', DiscountViewset)
router.register('onlinesubscriber', OnlineSubscriberViewset)
router.register('subscription', SubscriptionViewset)
router.register('services',ServicesViewset)
router.register('restore', RestoresViewset)
router.register('onlineuser', OnlineUserViewset)
router.register('downloadapp', DownloadAppViewset)
router.register('download', DownloadViewset)