# Generated by Django 3.2 on 2021-07-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210625_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuitymember',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='downloadapp',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
