# Generated by Django 3.2 on 2021-07-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210715_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('permission_menu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('permission_sub_menu', models.CharField(max_length=100)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.permissionmenu')),
            ],
        ),
    ]
